spring:
  datasource:
    url: jdbc:mysql://localhost:3306/subestacao?reconnect=true&useTimezone=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345

